const layout = [
  {
    name: '两面',
    id: 1,
    selected: true,
    totleTitle: ['其他', '正一', '正二', '正三', '正四', '正五', '正六'],
    items: [
      {
        title: '其他',
        data: [
          {title: '其他', label: '特单', name: 'SP_ODD'},
          {title: '其他', label: '特双', name: 'SP_EVEN'},
          {title: '其他', label: '特大', name: 'SP_OVER'},
          {title: '其他', label: '特小', name: 'SP_UNDER'},
          {title: '其他', label: '合单', name: 'SP_SODD'},
          {title: '其他', label: '合双', name: 'SP_SEVEN'},
          {title: '其他', label: '合大', name: 'SP_SOVER'},
          {title: '其他', label: '合小', name: 'SP_SUNDER'},
          {title: '其他', label: '总单', name: 'NA_ODD'},
          {title: '其他', label: '总双', name: 'NA_EVEN'},
          {title: '其他', label: '总大', name: 'NA_OVER'},
          {title: '其他', label: '总小', name: 'NA_UNDER'},
        ],
      },
      {
         title: '正一',
        data: [
          {title: '正一', label: '单', name: 'NO1_ODD'},
          {title: '正一', label: '双', name: 'NO1_EVEN'},
          {title: '正一', label: '大', name: 'NO1_OVER'},
          {title: '正一', label: '小', name: 'NO1_UNDER'},
          {title: '正一', label: '合单', name: 'NO1_SODD'},
          {title: '正一', label: '合双', name: 'NO1_SEVEN'},
          {title: '正一', label: '合大', name: 'NO1_SOVER'},
          {title: '正一', label: '合小', name: 'NO1_SUNDER'},
        ],
      },
      {
        title: '正二',
        data: [
          {title: '正二', label: '单', name: 'NO2_ODD'},
          {title: '正二', label: '双', name: 'NO2_EVEN'},
          {title: '正二', label: '大', name: 'NO2_OVER'},
          {title: '正二', label: '小', name: 'NO2_UNDER'},
          {title: '正二', label: '合单', name: 'NO2_SODD'},
          {title: '正二', label: '合双', name: 'NO2_SEVEN'},
          {title: '正二', label: '合大', name: 'NO2_SOVER'},
          {title: '正二', label: '合小', name: 'NO2_SUNDER'},
        ],
      },
      {
        title: '正三',
        data: [
          {title: '正三', label: '单', name: 'NO3_ODD'},
          {title: '正三', label: '双', name: 'NO3_EVEN'},
          {title: '正三', label: '大', name: 'NO3_OVER'},
          {title: '正三', label: '小', name: 'NO3_UNDER'},
          {title: '正三', label: '合单', name: 'NO3_SODD'},
          {title: '正三', label: '合双', name: 'NO3_SEVEN'},
          {title: '正三', label: '合大', name: 'NO3_SOVER'},
          {title: '正三', label: '合小', name: 'NO3_SUNDER'},
        ],
      },
      {
        title: '正四',
        data: [
          {title: '正四', label: '单', name: 'NO4_ODD'},
          {title: '正四', label: '双', name: 'NO4_EVEN'},
          {title: '正四', label: '大', name: 'NO4_OVER'},
          {title: '正四', label: '小', name: 'NO4_UNDER'},
          {title: '正四', label: '合单', name: 'NO4_SODD'},
          {title: '正四', label: '合双', name: 'NO4_SEVEN'},
          {title: '正四', label: '合大', name: 'NO4_SOVER'},
          {title: '正四', label: '合小', name: 'NO4_SUNDER'},
        ],
      },
      {
        title: '正五',
        data: [
          {title: '正五', label: '单', name: 'NO5_ODD'},
          {title: '正五', label: '双', name: 'NO5_EVEN'},
          {title: '正五', label: '大', name: 'NO5_OVER'},
          {title: '正五', label: '小', name: 'NO5_UNDER'},
          {title: '正五', label: '合单', name: 'NO5_SODD'},
          {title: '正五', label: '合双', name: 'NO5_SEVEN'},
          {title: '正五', label: '合大', name: 'NO5_SOVER'},
          {title: '正五', label: '合小', name: 'NO5_SUNDER'},
        ],
      },
      {
        title: '正六',
        data: [
          {title: '正六', label: '单', name: 'NO6_ODD'},
          {title: '正六', label: '双', name: 'NO6_EVEN'},
          {title: '正六', label: '大', name: 'NO6_OVER'},
          {title: '正六', label: '小', name: 'NO6_UNDER'},
          {title: '正六', label: '合单', name: 'NO6_SODD'},
          {title: '正六', label: '合双', name: 'NO6_SEVEN'},
          {title: '正六', label: '合大', name: 'NO6_SOVER'},
          {title: '正六', label: '合小', name: 'NO6_SUNDER'},
        ],
      },
    ],
  },
  {
    name: '特别号',
    id: 2,
    type: 'tebiehao',
    totleTitle: ['特码B', '特码A', '其他' ],
    items:[
      {
        title: '特码B',
        type: 'TMB',
        defaultSelected: true,
            data: [
              {title: '特码B', label: '01',name: 'B_SP01'},
              {title: '特码B', label: '02',name: 'B_SP02'},
              {title: '特码B', label: '03',name: 'B_SP03'},
              {title: '特码B', label: '04',name: 'B_SP04'},
              {title: '特码B', label: '05',name: 'B_SP05'},
              {title: '特码B', label: '06',name: 'B_SP06'},
              {title: '特码B', label: '07',name: 'B_SP07'},
              {title: '特码B', label: '08',name: 'B_SP08'},
              {title: '特码B', label: '09',name: 'B_SP09'},
              {title: '特码B', label: '10',name: 'B_SP10'},
              {title: '特码B', label: '11',name: 'B_SP11'},
              {title: '特码B', label: '12',name: 'B_SP12'},
              {title: '特码B', label: '13',name: 'B_SP13'},
              {title: '特码B', label: '14',name: 'B_SP14'},
              {title: '特码B', label: '15',name: 'B_SP15'},
              {title: '特码B', label: '16',name: 'B_SP16'},
              {title: '特码B', label: '17',name: 'B_SP17'},
              {title: '特码B', label: '18',name: 'B_SP18'},
              {title: '特码B', label: '19',name: 'B_SP19'},
              {title: '特码B', label: '20',name: 'B_SP20'},
              {title: '特码B', label: '21',name: 'B_SP21'},
              {title: '特码B', label: '22',name: 'B_SP22'},
              {title: '特码B', label: '23',name: 'B_SP23'},
              {title: '特码B', label: '24',name: 'B_SP24'},
              {title: '特码B', label: '25',name: 'B_SP25'},
              {title: '特码B', label: '26',name: 'B_SP26'},
              {title: '特码B', label: '27',name: 'B_SP27'},
              {title: '特码B', label: '28',name: 'B_SP28'},
              {title: '特码B', label: '29',name: 'B_SP29'},
              {title: '特码B', label: '30',name: 'B_SP30'},
              {title: '特码B', label: '31',name: 'B_SP31'},
              {title: '特码B', label: '32',name: 'B_SP32'},
              {title: '特码B', label: '33',name: 'B_SP33'},
              {title: '特码B', label: '34',name: 'B_SP34'},
              {title: '特码B', label: '35',name: 'B_SP35'},
              {title: '特码B', label: '36',name: 'B_SP36'},
              {title: '特码B', label: '37',name: 'B_SP37'},
              {title: '特码B', label: '38',name: 'B_SP38'},
              {title: '特码B', label: '39',name: 'B_SP39'},
              {title: '特码B', label: '40',name: 'B_SP40'},
              {title: '特码B', label: '41',name: 'B_SP41'},
              {title: '特码B', label: '42',name: 'B_SP42'},
              {title: '特码B', label: '43',name: 'B_SP43'},
              {title: '特码B', label: '44',name: 'B_SP44'},
              {title: '特码B', label: '45',name: 'B_SP45'},
              {title: '特码B', label: '46',name: 'B_SP46'},
              {title: '特码B', label: '47',name: 'B_SP47'},
              {title: '特码B', label: '48',name: 'B_SP48'},
              {title: '特码B', label: '49',name: 'B_SP49'},
            ],
      },
      {
            title: '特码A',
            type: 'TMA',
            defaultSelected: false,
            data: [
              {title: '特码A', label: '01',name: 'A_SP01'},
              {title: '特码A', label: '02',name: 'A_SP02'},
              {title: '特码A', label: '03',name: 'A_SP03'},
              {title: '特码A', label: '04',name: 'A_SP04'},
              {title: '特码A', label: '05',name: 'A_SP05'},
              {title: '特码A', label: '06',name: 'A_SP06'},
              {title: '特码A', label: '07',name: 'A_SP07'},
              {title: '特码A', label: '08',name: 'A_SP08'},
              {title: '特码A', label: '09',name: 'A_SP09'},
              {title: '特码A', label: '10',name: 'A_SP10'},
              {title: '特码A', label: '11',name: 'A_SP11'},
              {title: '特码A', label: '12',name: 'A_SP12'},
              {title: '特码A', label: '13',name: 'A_SP13'},
              {title: '特码A', label: '14',name: 'A_SP14'},
              {title: '特码A', label: '15',name: 'A_SP15'},
              {title: '特码A', label: '16',name: 'A_SP16'},
              {title: '特码A', label: '17',name: 'A_SP17'},
              {title: '特码A', label: '18',name: 'A_SP18'},
              {title: '特码A', label: '19',name: 'A_SP19'},
              {title: '特码A', label: '20',name: 'A_SP20'},
              {title: '特码A', label: '21',name: 'A_SP21'},
              {title: '特码A', label: '22',name: 'A_SP22'},
              {title: '特码A', label: '23',name: 'A_SP23'},
              {title: '特码A', label: '24',name: 'A_SP24'},
              {title: '特码A', label: '25',name: 'A_SP25'},
              {title: '特码A', label: '26',name: 'A_SP26'},
              {title: '特码A', label: '27',name: 'A_SP27'},
              {title: '特码A', label: '28',name: 'A_SP28'},
              {title: '特码A', label: '29',name: 'A_SP29'},
              {title: '特码A', label: '30',name: 'A_SP30'},
              {title: '特码A', label: '31',name: 'A_SP31'},
              {title: '特码A', label: '32',name: 'A_SP32'},
              {title: '特码A', label: '33',name: 'A_SP33'},
              {title: '特码A', label: '34',name: 'A_SP34'},
              {title: '特码A', label: '35',name: 'A_SP35'},
              {title: '特码A', label: '36',name: 'A_SP36'},
              {title: '特码A', label: '37',name: 'A_SP37'},
              {title: '特码A', label: '38',name: 'A_SP38'},
              {title: '特码A', label: '39',name: 'A_SP39'},
              {title: '特码A', label: '40',name: 'A_SP40'},
              {title: '特码A', label: '41',name: 'A_SP41'},
              {title: '特码A', label: '42',name: 'A_SP42'},
              {title: '特码A', label: '43',name: 'A_SP43'},
              {title: '特码A', label: '44',name: 'A_SP44'},
              {title: '特码A', label: '45',name: 'A_SP45'},
              {title: '特码A', label: '46',name: 'A_SP46'},
              {title: '特码A', label: '47',name: 'A_SP47'},
              {title: '特码A', label: '48',name: 'A_SP48'},
              {title: '特码A', label: '49',name: 'A_SP49'},
            ],
      },
      {
            title: '其他',
            type: 'OTHERS',
            defaultSelected: false,
            data: [
              {title: '其他', label: '特单', name: 'SP_ODD'},
              {title: '其他', label: '特双', name: 'SP_EVEN'},
              {title: '其他', label: '特大', name: 'SP_OVER'},
              {title: '其他', label: '特小', name: 'SP_UNDER'},
              {title: '其他', label: '尾大', name: 'SF_OVER'},
              {title: '其他', label: '合单', name: 'SP_SODD'},
              {title: '其他', label: '合双', name: 'SP_SEVEN'},
              {title: '其他', label: '合大', name: 'SP_SOVER'},
              {title: '其他', label: '合小', name: 'SP_SUNDER'},
              {title: '其他', label: '尾小', name: 'SF_UNDER'},
              {title: '其他', label: '大双', name: 'HS_EO'},
              {title: '其他', label: '小双', name: 'HS_EU'},
              {title: '其他', label: '大单', name: 'HS_OO'},
              {title: '其他', label: '小单', name: 'HS_OU'},
            ],
          },
        ],
  },
  {
    name: '正码',
    id: 3,
    items:[
      {
        title: '正码',
        data: [
          {title: '正码', label: '01', name: 'NA01'},
          {title: '正码', label: '02', name: 'NA02'},
          {title: '正码', label: '03', name: 'NA03'},
          {title: '正码', label: '04', name: 'NA04'},
          {title: '正码', label: '05', name: 'NA05'},
          {title: '正码', label: '06', name: 'NA06'},
          {title: '正码', label: '07', name: 'NA07'},
          {title: '正码', label: '08', name: 'NA08'},
          {title: '正码', label: '09', name: 'NA09'},
          {title: '正码', label: '10', name: 'NA10'},
          {title: '正码', label: '11', name: 'NA11'},
          {title: '正码', label: '12', name: 'NA12'},
          {title: '正码', label: '13', name: 'NA13'},
          {title: '正码', label: '14', name: 'NA14'},
          {title: '正码', label: '15', name: 'NA15'},
          {title: '正码', label: '16', name: 'NA16'},
          {title: '正码', label: '17', name: 'NA17'},
          {title: '正码', label: '18', name: 'NA18'},
          {title: '正码', label: '19', name: 'NA19'},
          {title: '正码', label: '20', name: 'NA20'},
          {title: '正码', label: '21', name: 'NA21'},
          {title: '正码', label: '22', name: 'NA22'},
          {title: '正码', label: '23', name: 'NA23'},
          {title: '正码', label: '24', name: 'NA24'},
          {title: '正码', label: '25', name: 'NA25'},
          {title: '正码', label: '26', name: 'NA26'},
          {title: '正码', label: '27', name: 'NA27'},
          {title: '正码', label: '28', name: 'NA28'},
          {title: '正码', label: '29', name: 'NA29'},
          {title: '正码', label: '30', name: 'NA30'},
          {title: '正码', label: '31', name: 'NA31'},
          {title: '正码', label: '32', name: 'NA32'},
          {title: '正码', label: '33', name: 'NA33'},
          {title: '正码', label: '34', name: 'NA34'},
          {title: '正码', label: '35', name: 'NA35'},
          {title: '正码', label: '36', name: 'NA36'},
          {title: '正码', label: '37', name: 'NA37'},
          {title: '正码', label: '38', name: 'NA38'},
          {title: '正码', label: '39', name: 'NA39'},
          {title: '正码', label: '40', name: 'NA40'},
          {title: '正码', label: '41', name: 'NA41'},
          {title: '正码', label: '42', name: 'NA42'},
          {title: '正码', label: '43', name: 'NA43'},
          {title: '正码', label: '44', name: 'NA44'},
          {title: '正码', label: '45', name: 'NA45'},
          {title: '正码', label: '46', name: 'NA46'},
          {title: '正码', label: '47', name: 'NA47'},
          {title: '正码', label: '48', name: 'NA48'},
          {title: '正码', label: '49', name: 'NA49'},
        ],
      },
    ],
  },
  {
    name: '正码特',
    id: 4,
    type: 'zhengmate',
    totleTitle: ['正特一', '正特二', '正特三', '正特四', '正特五', '正特六'],
        defaultSelected: true,
        items: [
          {
          title: '正特一',
          type: 'N1',
          data: [
            {title: '正特一', label: '01', name: 'N101'},
            {title: '正特一', label: '02', name: 'N102'},
            {title: '正特一', label: '03', name: 'N103'},
            {title: '正特一', label: '04', name: 'N104'},
            {title: '正特一', label: '05', name: 'N105'},
            {title: '正特一', label: '06', name: 'N106'},
            {title: '正特一', label: '07', name: 'N107'},
            {title: '正特一', label: '08', name: 'N108'},
            {title: '正特一', label: '09', name: 'N109'},
            {title: '正特一', label: '10', name: 'N110'},
            {title: '正特一', label: '11', name: 'N111'},
            {title: '正特一', label: '12', name: 'N112'},
            {title: '正特一', label: '13', name: 'N113'},
            {title: '正特一', label: '14', name: 'N114'},
            {title: '正特一', label: '15', name: 'N115'},
            {title: '正特一', label: '16', name: 'N116'},
            {title: '正特一', label: '17', name: 'N117'},
            {title: '正特一', label: '18', name: 'N118'},
            {title: '正特一', label: '19', name: 'N119'},
            {title: '正特一', label: '20', name: 'N120'},
            {title: '正特一', label: '21', name: 'N121'},
            {title: '正特一', label: '22', name: 'N122'},
            {title: '正特一', label: '23', name: 'N123'},
            {title: '正特一', label: '24', name: 'N124'},
            {title: '正特一', label: '25', name: 'N125'},
            {title: '正特一', label: '26', name: 'N126'},
            {title: '正特一', label: '27', name: 'N127'},
            {title: '正特一', label: '28', name: 'N128'},
            {title: '正特一', label: '29', name: 'N129'},
            {title: '正特一', label: '30', name: 'N130'},
            {title: '正特一', label: '31', name: 'N131'},
            {title: '正特一', label: '32', name: 'N132'},
            {title: '正特一', label: '33', name: 'N133'},
            {title: '正特一', label: '34', name: 'N134'},
            {title: '正特一', label: '35', name: 'N135'},
            {title: '正特一', label: '36', name: 'N136'},
            {title: '正特一', label: '37', name: 'N137'},
            {title: '正特一', label: '38', name: 'N138'},
            {title: '正特一', label: '39', name: 'N139'},
            {title: '正特一', label: '40', name: 'N140'},
            {title: '正特一', label: '41', name: 'N141'},
            {title: '正特一', label: '42', name: 'N142'},
            {title: '正特一', label: '43', name: 'N143'},
            {title: '正特一', label: '44', name: 'N144'},
            {title: '正特一', label: '45', name: 'N145'},
            {title: '正特一', label: '46', name: 'N146'},
            {title: '正特一', label: '47', name: 'N147'},
            {title: '正特一', label: '48', name: 'N148'},
            {title: '正特一', label: '49', name: 'N149'},
          ],
        },
        {
          title: '正特二',
          type: 'N2',
          data: [
            {title: '正特二', label: '01', name: 'N201'},
            {title: '正特二', label: '02', name: 'N202'},
            {title: '正特二', label: '03', name: 'N203'},
            {title: '正特二', label: '04', name: 'N204'},
            {title: '正特二', label: '05', name: 'N205'},
            {title: '正特二', label: '06', name: 'N206'},
            {title: '正特二', label: '07', name: 'N207'},
            {title: '正特二', label: '08', name: 'N208'},
            {title: '正特二', label: '09', name: 'N209'},
            {title: '正特二', label: '10', name: 'N210'},
            {title: '正特二', label: '11', name: 'N211'},
            {title: '正特二', label: '12', name: 'N212'},
            {title: '正特二', label: '13', name: 'N213'},
            {title: '正特二', label: '14', name: 'N214'},
            {title: '正特二', label: '15', name: 'N215'},
            {title: '正特二', label: '16', name: 'N216'},
            {title: '正特二', label: '17', name: 'N217'},
            {title: '正特二', label: '18', name: 'N218'},
            {title: '正特二', label: '19', name: 'N219'},
            {title: '正特二', label: '20', name: 'N220'},
            {title: '正特二', label: '21', name: 'N221'},
            {title: '正特二', label: '22', name: 'N222'},
            {title: '正特二', label: '23', name: 'N223'},
            {title: '正特二', label: '24', name: 'N224'},
            {title: '正特二', label: '25', name: 'N225'},
            {title: '正特二', label: '26', name: 'N226'},
            {title: '正特二', label: '27', name: 'N227'},
            {title: '正特二', label: '28', name: 'N228'},
            {title: '正特二', label: '29', name: 'N229'},
            {title: '正特二', label: '30', name: 'N230'},
            {title: '正特二', label: '31', name: 'N231'},
            {title: '正特二', label: '32', name: 'N232'},
            {title: '正特二', label: '33', name: 'N233'},
            {title: '正特二', label: '34', name: 'N234'},
            {title: '正特二', label: '35', name: 'N235'},
            {title: '正特二', label: '36', name: 'N236'},
            {title: '正特二', label: '37', name: 'N237'},
            {title: '正特二', label: '38', name: 'N238'},
            {title: '正特二', label: '39', name: 'N239'},
            {title: '正特二', label: '40', name: 'N240'},
            {title: '正特二', label: '41', name: 'N241'},
            {title: '正特二', label: '42', name: 'N242'},
            {title: '正特二', label: '43', name: 'N243'},
            {title: '正特二', label: '44', name: 'N244'},
            {title: '正特二', label: '45', name: 'N245'},
            {title: '正特二', label: '46', name: 'N246'},
            {title: '正特二', label: '47', name: 'N247'},
            {title: '正特二', label: '48', name: 'N248'},
            {title: '正特二', label: '49', name: 'N249'},
          ],
        },
        {
          title: '正特三',
          type: 'N3',
          data: [
             {title: '正特三', label: '01', name: 'N301'},
             {title: '正特三', label: '02', name: 'N302'},
             {title: '正特三', label: '03', name: 'N303'},
             {title: '正特三', label: '04', name: 'N304'},
             {title: '正特三', label: '05', name: 'N305'},
             {title: '正特三', label: '06', name: 'N306'},
             {title: '正特三', label: '07', name: 'N307'},
             {title: '正特三', label: '08', name: 'N308'},
             {title: '正特三', label: '09', name: 'N309'},
             {title: '正特三', label: '10', name: 'N310'},
             {title: '正特三', label: '11', name: 'N311'},
             {title: '正特三', label: '12', name: 'N312'},
             {title: '正特三', label: '13', name: 'N313'},
             {title: '正特三', label: '14', name: 'N314'},
             {title: '正特三', label: '15', name: 'N315'},
             {title: '正特三', label: '16', name: 'N316'},
             {title: '正特三', label: '17', name: 'N317'},
             {title: '正特三', label: '18', name: 'N318'},
             {title: '正特三', label: '19', name: 'N319'},
             {title: '正特三', label: '20', name: 'N320'},
             {title: '正特三', label: '21', name: 'N321'},
             {title: '正特三', label: '22', name: 'N322'},
             {title: '正特三', label: '23', name: 'N323'},
             {title: '正特三', label: '24', name: 'N324'},
             {title: '正特三', label: '25', name: 'N325'},
             {title: '正特三', label: '26', name: 'N326'},
             {title: '正特三', label: '27', name: 'N327'},
             {title: '正特三', label: '28', name: 'N328'},
             {title: '正特三', label: '29', name: 'N329'},
             {title: '正特三', label: '30', name: 'N330'},
             {title: '正特三', label: '31', name: 'N331'},
             {title: '正特三', label: '32', name: 'N332'},
             {title: '正特三', label: '33', name: 'N333'},
             {title: '正特三', label: '34', name: 'N334'},
             {title: '正特三', label: '35', name: 'N335'},
             {title: '正特三', label: '36', name: 'N336'},
             {title: '正特三', label: '37', name: 'N337'},
             {title: '正特三', label: '38', name: 'N338'},
             {title: '正特三', label: '39', name: 'N339'},
             {title: '正特三', label: '40', name: 'N340'},
             {title: '正特三', label: '41', name: 'N341'},
             {title: '正特三', label: '42', name: 'N342'},
             {title: '正特三', label: '43', name: 'N343'},
             {title: '正特三', label: '44', name: 'N344'},
             {title: '正特三', label: '45', name: 'N345'},
             {title: '正特三', label: '46', name: 'N346'},
             {title: '正特三', label: '47', name: 'N347'},
             {title: '正特三', label: '48', name: 'N348'},
             {title: '正特三', label: '49', name: 'N349'},
          ],
        },
        {
          title: '正特四',
          type: 'N4',
          data: [
            {title: '正特四', label: '01', name: 'N401'},
            {title: '正特四', label: '02', name: 'N402'},
            {title: '正特四', label: '03', name: 'N403'},
            {title: '正特四', label: '04', name: 'N404'},
            {title: '正特四', label: '05', name: 'N405'},
            {title: '正特四', label: '06', name: 'N406'},
            {title: '正特四', label: '07', name: 'N407'},
            {title: '正特四', label: '08', name: 'N408'},
            {title: '正特四', label: '09', name: 'N409'},
            {title: '正特四', label: '10', name: 'N410'},
            {title: '正特四', label: '11', name: 'N411'},
            {title: '正特四', label: '12', name: 'N412'},
            {title: '正特四', label: '13', name: 'N413'},
            {title: '正特四', label: '14', name: 'N414'},
            {title: '正特四', label: '15', name: 'N415'},
            {title: '正特四', label: '16', name: 'N416'},
            {title: '正特四', label: '17', name: 'N417'},
            {title: '正特四', label: '18', name: 'N418'},
            {title: '正特四', label: '19', name: 'N419'},
            {title: '正特四', label: '20', name: 'N420'},
            {title: '正特四', label: '21', name: 'N421'},
            {title: '正特四', label: '22', name: 'N422'},
            {title: '正特四', label: '23', name: 'N423'},
            {title: '正特四', label: '24', name: 'N424'},
            {title: '正特四', label: '25', name: 'N425'},
            {title: '正特四', label: '26', name: 'N426'},
            {title: '正特四', label: '27', name: 'N427'},
            {title: '正特四', label: '28', name: 'N428'},
            {title: '正特四', label: '29', name: 'N429'},
            {title: '正特四', label: '30', name: 'N430'},
            {title: '正特四', label: '31', name: 'N431'},
            {title: '正特四', label: '32', name: 'N432'},
            {title: '正特四', label: '33', name: 'N433'},
            {title: '正特四', label: '34', name: 'N434'},
            {title: '正特四', label: '35', name: 'N435'},
            {title: '正特四', label: '36', name: 'N436'},
            {title: '正特四', label: '37', name: 'N437'},
            {title: '正特四', label: '38', name: 'N438'},
            {title: '正特四', label: '39', name: 'N439'},
            {title: '正特四', label: '40', name: 'N440'},
            {title: '正特四', label: '41', name: 'N441'},
            {title: '正特四', label: '42', name: 'N442'},
            {title: '正特四', label: '43', name: 'N443'},
            {title: '正特四', label: '44', name: 'N444'},
            {title: '正特四', label: '45', name: 'N445'},
            {title: '正特四', label: '46', name: 'N446'},
            {title: '正特四', label: '47', name: 'N447'},
            {title: '正特四', label: '48', name: 'N448'},
            {title: '正特四', label: '49', name: 'N449'},
          ],
        },
        {
          title: '正特五',
          type: 'N5',
          data: [
            {title: '正特五', label: '01', name: 'N501'},
            {title: '正特五', label: '02', name: 'N502'},
            {title: '正特五', label: '03', name: 'N503'},
            {title: '正特五', label: '04', name: 'N504'},
            {title: '正特五', label: '05', name: 'N505'},
            {title: '正特五', label: '06', name: 'N506'},
            {title: '正特五', label: '07', name: 'N507'},
            {title: '正特五', label: '08', name: 'N508'},
            {title: '正特五', label: '09', name: 'N509'},
            {title: '正特五', label: '10', name: 'N510'},
            {title: '正特五', label: '11', name: 'N511'},
            {title: '正特五', label: '12', name: 'N512'},
            {title: '正特五', label: '13', name: 'N513'},
            {title: '正特五', label: '14', name: 'N514'},
            {title: '正特五', label: '15', name: 'N515'},
            {title: '正特五', label: '16', name: 'N516'},
            {title: '正特五', label: '17', name: 'N517'},
            {title: '正特五', label: '18', name: 'N518'},
            {title: '正特五', label: '19', name: 'N519'},
            {title: '正特五', label: '20', name: 'N520'},
            {title: '正特五', label: '21', name: 'N521'},
            {title: '正特五', label: '22', name: 'N522'},
            {title: '正特五', label: '23', name: 'N523'},
            {title: '正特五', label: '24', name: 'N524'},
            {title: '正特五', label: '25', name: 'N525'},
            {title: '正特五', label: '26', name: 'N526'},
            {title: '正特五', label: '27', name: 'N527'},
            {title: '正特五', label: '28', name: 'N528'},
            {title: '正特五', label: '29', name: 'N529'},
            {title: '正特五', label: '30', name: 'N530'},
            {title: '正特五', label: '31', name: 'N531'},
            {title: '正特五', label: '32', name: 'N532'},
            {title: '正特五', label: '33', name: 'N533'},
            {title: '正特五', label: '34', name: 'N534'},
            {title: '正特五', label: '35', name: 'N535'},
            {title: '正特五', label: '36', name: 'N536'},
            {title: '正特五', label: '37', name: 'N537'},
            {title: '正特五', label: '38', name: 'N538'},
            {title: '正特五', label: '39', name: 'N539'},
            {title: '正特五', label: '40', name: 'N540'},
            {title: '正特五', label: '41', name: 'N541'},
            {title: '正特五', label: '42', name: 'N542'},
            {title: '正特五', label: '43', name: 'N543'},
            {title: '正特五', label: '44', name: 'N544'},
            {title: '正特五', label: '45', name: 'N545'},
            {title: '正特五', label: '46', name: 'N546'},
            {title: '正特五', label: '47', name: 'N547'},
            {title: '正特五', label: '48', name: 'N548'},
            {title: '正特五', label: '49', name: 'N549'},
          ],
        },
        {
          title: '正特六',
          type: 'N6',
          data: [
           {title: '正特六', label: '01', name: 'N601'},
           {title: '正特六', label: '02', name: 'N602'},
           {title: '正特六', label: '03', name: 'N603'},
           {title: '正特六', label: '04', name: 'N604'},
           {title: '正特六', label: '05', name: 'N605'},
           {title: '正特六', label: '06', name: 'N606'},
           {title: '正特六', label: '07', name: 'N607'},
           {title: '正特六', label: '08', name: 'N608'},
           {title: '正特六', label: '09', name: 'N609'},
           {title: '正特六', label: '10', name: 'N610'},
           {title: '正特六', label: '11', name: 'N611'},
           {title: '正特六', label: '12', name: 'N612'},
           {title: '正特六', label: '13', name: 'N613'},
           {title: '正特六', label: '14', name: 'N614'},
           {title: '正特六', label: '15', name: 'N615'},
           {title: '正特六', label: '16', name: 'N616'},
           {title: '正特六', label: '17', name: 'N617'},
           {title: '正特六', label: '18', name: 'N618'},
           {title: '正特六', label: '19', name: 'N619'},
           {title: '正特六', label: '20', name: 'N620'},
           {title: '正特六', label: '21', name: 'N621'},
           {title: '正特六', label: '22', name: 'N622'},
           {title: '正特六', label: '23', name: 'N623'},
           {title: '正特六', label: '24', name: 'N624'},
           {title: '正特六', label: '25', name: 'N625'},
           {title: '正特六', label: '26', name: 'N626'},
           {title: '正特六', label: '27', name: 'N627'},
           {title: '正特六', label: '28', name: 'N628'},
           {title: '正特六', label: '29', name: 'N629'},
           {title: '正特六', label: '30', name: 'N630'},
           {title: '正特六', label: '31', name: 'N631'},
           {title: '正特六', label: '32', name: 'N632'},
           {title: '正特六', label: '33', name: 'N633'},
           {title: '正特六', label: '34', name: 'N634'},
           {title: '正特六', label: '35', name: 'N635'},
           {title: '正特六', label: '36', name: 'N636'},
           {title: '正特六', label: '37', name: 'N637'},
           {title: '正特六', label: '38', name: 'N638'},
           {title: '正特六', label: '39', name: 'N639'},
           {title: '正特六', label: '40', name: 'N640'},
           {title: '正特六', label: '41', name: 'N641'},
           {title: '正特六', label: '42', name: 'N642'},
           {title: '正特六', label: '43', name: 'N643'},
           {title: '正特六', label: '44', name: 'N644'},
           {title: '正特六', label: '45', name: 'N645'},
           {title: '正特六', label: '46', name: 'N646'},
           {title: '正特六', label: '47', name: 'N647'},
           {title: '正特六', label: '48', name: 'N648'},
           {title: '正特六', label: '49', name: 'N649'},
          ],
        },
      ],
  },
  {
    name: '正码 1-6',
    id: 5,
    totleTitle: ['正码一', '正码二', '正码三', '正码四', '正码五', '正码六'],
    items: [
      {
        type: 'normal_grid',
        name: '正码一',
        data: [
          {title: '正码一', label: '单', name: 'NO1_ODD'},
          {title: '正码一', label: '双', name: 'NO1_EVEN'},
          {title: '正码一', label: '大', name: 'NO1_OVER'},
          {title: '正码一', label: '小', name: 'NO1_UNDER'},
          {title: '正码一', label: '合单', name: 'NO1_SODD'},
          {title: '正码一', label: '合双', name: 'NO1_SEVEN'},
          {title: '正码一', label: '合大', name: 'NO1_SOVER'},
          {title: '正码一', label: '合小', name: 'NO1_SUNDER'},
          {title: '正码一', label: '尾大', name: 'NO1_FOVER'},
          {title: '正码一', label: '尾小', name: 'NO1_FUNDER'},
          {title: '正码一', label: '红波', name: 'NO1_R'},
          {title: '正码一', label: '绿波', name: 'NO1_G'},
          {title: '正码一', label: '蓝波', name: 'NO1_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正码二',
        data: [
         {title: '正码二', label: '单', name: 'NO2_ODD'},
         {title: '正码二', label: '双', name: 'NO2_EVEN'},
         {title: '正码二', label: '大', name: 'NO2_OVER'},
         {title: '正码二', label: '小', name: 'NO2_UNDER'},
         {title: '正码二', label: '合单', name: 'NO2_SODD'},
         {title: '正码二', label: '合双', name: 'NO2_SEVEN'},
         {title: '正码二', label: '合大', name: 'NO2_SOVER'},
         {title: '正码二', label: '合小', name: 'NO2_SUNDER'},
         {title: '正码二', label: '尾大', name: 'NO2_FOVER'},
         {title: '正码二', label: '尾小', name: 'NO2_FUNDER'},
         {title: '正码二', label: '红波', name: 'NO2_R'},
         {title: '正码二', label: '绿波', name: 'NO2_G'},
         {title: '正码二', label: '蓝波', name: 'NO2_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正码三',
        data: [
           {title: '正码三', label: '单', name: 'NO3_ODD'},
           {title: '正码三', label: '双', name: 'NO3_EVEN'},
           {title: '正码三', label: '大', name: 'NO3_OVER'},
           {title: '正码三', label: '小', name: 'NO3_UNDER'},
           {title: '正码三', label: '合单', name: 'NO3_SODD'},
           {title: '正码三', label: '合双', name: 'NO3_SEVEN'},
           {title: '正码三', label: '合大', name: 'NO3_SOVER'},
           {title: '正码三', label: '合小', name: 'NO3_SUNDER'},
           {title: '正码三', label: '尾大', name: 'NO3_FOVER'},
           {title: '正码三', label: '尾小', name: 'NO3_FUNDER'},
           {title: '正码三', label: '红波', name: 'NO3_R'},
           {title: '正码三', label: '绿波', name: 'NO3_G'},
           {title: '正码三', label: '蓝波', name: 'NO3_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正码四',
        data: [
          {title: '正码四', label: '单', name: 'NO4_ODD'},
          {title: '正码四', label: '双', name: 'NO4_EVEN'},
          {title: '正码四', label: '大', name: 'NO4_OVER'},
          {title: '正码四', label: '小', name: 'NO4_UNDER'},
          {title: '正码四', label: '合单', name: 'NO4_SODD'},
          {title: '正码四', label: '合双', name: 'NO4_SEVEN'},
          {title: '正码四', label: '合大', name: 'NO4_SOVER'},
          {title: '正码四', label: '合小', name: 'NO4_SUNDER'},
          {title: '正码四', label: '尾大', name: 'NO4_FOVER'},
          {title: '正码四', label: '尾小', name: 'NO4_FUNDER'},
          {title: '正码四', label: '红波', name: 'NO4_R'},
          {title: '正码四', label: '绿波', name: 'NO4_G'},
          {title: '正码四', label: '蓝波', name: 'NO4_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正码五',
        data: [
          {title: '正码五', label: '单', name: 'NO5_ODD'},
          {title: '正码五', label: '双', name: 'NO5_EVEN'},
          {title: '正码五', label: '大', name: 'NO5_OVER'},
          {title: '正码五', label: '小', name: 'NO5_UNDER'},
          {title: '正码五', label: '合单', name: 'NO5_SODD'},
          {title: '正码五', label: '合双', name: 'NO5_SEVEN'},
          {title: '正码五', label: '合大', name: 'NO5_SOVER'},
          {title: '正码五', label: '合小', name: 'NO5_SUNDER'},
          {title: '正码五', label: '尾大', name: 'NO5_FOVER'},
          {title: '正码五', label: '尾小', name: 'NO5_FUNDER'},
          {title: '正码五', label: '红波', name: 'NO5_R'},
          {title: '正码五', label: '绿波', name: 'NO5_G'},
          {title: '正码五', label: '蓝波', name: 'NO5_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正码六',
        data: [
          {title: '正码六', label: '单', name: 'NO6_ODD'},
          {title: '正码六', label: '双', name: 'NO6_EVEN'},
          {title: '正码六', label: '大', name: 'NO6_OVER'},
          {title: '正码六', label: '小', name: 'NO6_UNDER'},
          {title: '正码六', label: '合单', name: 'NO6_SODD'},
          {title: '正码六', label: '合双', name: 'NO6_SEVEN'},
          {title: '正码六', label: '合大', name: 'NO6_SOVER'},
          {title: '正码六', label: '合小', name: 'NO6_SUNDER'},
          {title: '正码六', label: '尾大', name: 'NO6_FOVER'},
          {title: '正码六', label: '尾小', name: 'NO6_FUNDER'},
          {title: '正码六', label: '红波', name: 'NO6_R'},
          {title: '正码六', label: '绿波', name: 'NO6_G'},
          {title: '正码六', label: '蓝波', name: 'NO6_B'},
        ],
      },
    ],
  },
  {
    name: '正码过关',
    id: 6,
    type: 'zhengmaguoguan',
    totleTitle: ['正码一', '正码二', '正码三', '正码四', '正码五', '正码六'],
    items: [
      {
        type: 'normal_grid',
        name: '正一',
        data: [
          {title: '正一', label: '单', type: 'z1', name: 'NAP1_ODD'},
          {title: '正一', label: '双', type: 'z1', name: 'NAP1_EVEN'},
          {title: '正一', label: '大', type: 'z1', name: 'NAP1_OVER'},
          {title: '正一', label: '小', type: 'z1', name: 'NAP1_UNDER'},
          {title: '正一', label: '合单', type: 'z1', name: 'NAP1_SODD'},
          {title: '正一', label: '合双', type: 'z1', name: 'NAP1_SEVEN'},
          {title: '正一', label: '合大', type: 'z1', name: 'NAP1_SOVER'},
          {title: '正一', label: '合小', type: 'z1', name: 'NAP1_SUNDER'},
          {title: '正一', label: '尾大', type: 'z1', name: 'NAP1_FOVER'},
          {title: '正一', label: '尾小', type: 'z1', name: 'NAP1_FUNDER'},
          {title: '正一', label: '红', type: 'z1', name: 'NAP1_R'},
          {title: '正一', label: '绿', type: 'z1', name: 'NAP1_G'},
          {title: '正一', label: '蓝', type: 'z1', name: 'NAP1_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正二',
        data: [
          {title: '正二', label: '单', type: 'z2', name: 'NAP2_ODD'},
          {title: '正二', label: '双', type: 'z2', name: 'NAP2_EVEN'},
          {title: '正二', label: '大', type: 'z2', name: 'NAP2_OVER'},
          {title: '正二', label: '小', type: 'z2', name: 'NAP2_UNDER'},
          {title: '正二', label: '合单', type: 'z2', name: 'NAP2_SODD'},
          {title: '正二', label: '合双', type: 'z2', name: 'NAP2_SEVEN'},
          {title: '正二', label: '合大', type: 'z2', name: 'NAP2_SOVER'},
          {title: '正二', label: '合小', type: 'z2', name: 'NAP2_SUNDER'},
          {title: '正二', label: '尾大', type: 'z2', name: 'NAP2_FOVER'},
          {title: '正二', label: '尾小', type: 'z2', name: 'NAP2_FUNDER'},
          {title: '正二', label: '红', type: 'z2', name: 'NAP2_R'},
          {title: '正二', label: '绿', type: 'z2', name: 'NAP2_G'},
          {title: '正二', label: '蓝', type: 'z2', name: 'NAP2_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正三',
        data: [
          {title: '正三', label: '单', type: 'z3', name: 'NAP3_ODD'},
          {title: '正三', label: '双', type: 'z3', name: 'NAP3_EVEN'},
          {title: '正三', label: '大', type: 'z3', name: 'NAP3_OVER'},
          {title: '正三', label: '小', type: 'z3', name: 'NAP3_UNDER'},
          {title: '正三', label: '合单', type: 'z3', name: 'NAP3_SODD'},
          {title: '正三', label: '合双', type: 'z3', name: 'NAP3_SEVEN'},
          {title: '正三', label: '合大', type: 'z3', name: 'NAP3_SOVER'},
          {title: '正三', label: '合小', type: 'z3', name: 'NAP3_SUNDER'},
          {title: '正三', label: '尾大', type: 'z3', name: 'NAP3_FOVER'},
          {title: '正三', label: '尾小', type: 'z3', name: 'NAP3_FUNDER'},
          {title: '正三', label: '红', type: 'z3', name: 'NAP3_R'},
          {title: '正三', label: '绿', type: 'z3', name: 'NAP3_G'},
          {title: '正三', label: '蓝', type: 'z3', name: 'NAP3_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正四',
        data: [
          {title: '正四', label: '单', type: 'z4', name: 'NAP4_ODD'},
          {title: '正四', label: '双', type: 'z4', name: 'NAP4_EVEN'},
          {title: '正四', label: '大', type: 'z4', name: 'NAP4_OVER'},
          {title: '正四', label: '小', type: 'z4', name: 'NAP4_UNDER'},
          {title: '正四', label: '合单', type: 'z4', name: 'NAP4_SODD'},
          {title: '正四', label: '合双', type: 'z4', name: 'NAP4_SEVEN'},
          {title: '正四', label: '合大', type: 'z4', name: 'NAP4_SOVER'},
          {title: '正四', label: '合小', type: 'z4', name: 'NAP4_SUNDER'},
          {title: '正四', label: '尾大', type: 'z4', name: 'NAP4_FOVER'},
          {title: '正四', label: '尾小', type: 'z4', name: 'NAP4_FUNDER'},
          {title: '正四', label: '红', type: 'z4', name: 'NAP4_R'},
          {title: '正四', label: '绿', type: 'z4', name: 'NAP4_G'},
          {title: '正四', label: '蓝', type: 'z4', name: 'NAP4_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正五',
        data: [
          {title: '正五', label: '单', type: 'z5', name: 'NAP5_ODD'},
          {title: '正五', label: '双', type: 'z5', name: 'NAP5_EVEN'},
          {title: '正五', label: '大', type: 'z5', name: 'NAP5_OVER'},
          {title: '正五', label: '小', type: 'z5', name: 'NAP5_UNDER'},
          {title: '正五', label: '合单', type: 'z5', name: 'NAP5_SODD'},
          {title: '正五', label: '合双', type: 'z5', name: 'NAP5_SEVEN'},
          {title: '正五', label: '合大', type: 'z5', name: 'NAP5_SOVER'},
          {title: '正五', label: '合小', type: 'z5', name: 'NAP5_SUNDER'},
          {title: '正五', label: '尾大', type: 'z5', name: 'NAP5_FOVER'},
          {title: '正五', label: '尾小', type: 'z5', name: 'NAP5_FUNDER'},
          {title: '正五', label: '红', type: 'z5', name: 'NAP5_R'},
          {title: '正五', label: '绿', type: 'z5', name: 'NAP5_G'},
          {title: '正五', label: '蓝', type: 'z5', name: 'NAP5_B'},
        ],
      },
      {
        type: 'normal_grid',
        name: '正六',
        data: [
          {title: '正六', label: '单', type: 'z6', name: 'NAP6_ODD'},
          {title: '正六', label: '双', type: 'z6', name: 'NAP6_EVEN'},
          {title: '正六', label: '大', type: 'z6', name: 'NAP6_OVER'},
          {title: '正六', label: '小', type: 'z6', name: 'NAP6_UNDER'},
          {title: '正六', label: '合单', type: 'z6', name: 'NAP6_SODD'},
          {title: '正六', label: '合双', type: 'z6', name: 'NAP6_SEVEN'},
          {title: '正六', label: '合大', type: 'z6', name: 'NAP6_SOVER'},
          {title: '正六', label: '合小', type: 'z6', name: 'NAP6_SUNDER'},
          {title: '正六', label: '尾大', type: 'z6', name: 'NAP6_FOVER'},
          {title: '正六', label: '尾小', type: 'z6', name: 'NAP6_FUNDER'},
          {title: '正六', label: '红', type: 'z6', name: 'NAP6_R'},
          {title: '正六', label: '绿', type: 'z6', name: 'NAP6_G'},
          {title: '正六', label: '蓝', type: 'z6', name: 'NAP6_B'},
        ],
      },
    ],
  },
  {
    name: '连码',
    id: 6,
    type: 'lianma',
    totleTitle: ['四全中', '三全中', '三中二', '二全中', '二中特', '特串'],
    data: [
      {label: '01'},
      {label: '02'},
      {label: '03'},
      {label: '04'},
      {label: '05'},
      {label: '06'},
      {label: '07'},
      {label: '08'},
      {label: '09'},
      {label: '10'},
      {label: '11'},
      {label: '12'},
      {label: '13'},
      {label: '14'},
      {label: '15'},
      {label: '16'},
      {label: '17'},
      {label: '18'},
      {label: '19'},
      {label: '20'},
      {label: '21'},
      {label: '22'},
      {label: '23'},
      {label: '24'},
      {label: '25'},
      {label: '26'},
      {label: '27'},
      {label: '28'},
      {label: '29'},
      {label: '30'},
      {label: '31'},
      {label: '32'},
      {label: '33'},
      {label: '34'},
      {label: '35'},
      {label: '36'},
      {label: '37'},
      {label: '38'},
      {label: '39'},
      {label: '40'},
      {label: '41'},
      {label: '42'},
      {label: '43'},
      {label: '44'},
      {label: '45'},
      {label: '46'},
      {label: '47'},
      {label: '48'},
      {label: '49'},
    ],
  },
  {
    name: '连肖',
    id: 8,
    type: 'lianxiao',
    totleTitle: ['二肖连', '三肖连', '四肖连', '五肖连'],
    tabs: ['LX2', 'LX3', 'LX4', 'LX5'],
    items: [
      {
        title: '二肖连',
        data: [
          {label: '鼠', type: 'A1', numbers: "10/22/34/46"},
          {label: '牛', type: 'A2', numbers: "09/21/33/45"},
          {label: '虎', type: 'A3', numbers: "08/20/32/44"},
          {label: '兔', type: 'A4', numbers: "07/19/31/43"},
          {label: '龙', type: 'A5', numbers: "06/18/30/42"},
          {label: '蛇', type: 'A6', numbers: "05/17/29/41"},
          {label: '马', type: 'A7', numbers: "04/16/28/40"},
          {label: '羊', type: 'A8', numbers: "03/15/27/39"},
          {label: '猴', type: 'A9', numbers: "02/14/26/38"},
          {label: '鸡', type: 'AA', numbers: "01/13/25/37/49"},
          {label: '狗', type: 'AB', numbers: "12/24/36/48"},
          {label: '猪', type: 'AC', numbers: "11/23/35/47"},
        ],
      },
      {
        title: '三肖连',
        data: [
          {label: '鼠', type: 'B1', numbers: "10/22/34/46"},
          {label: '牛', type: 'B2', numbers: "09/21/33/45"},
          {label: '虎', type: 'B3', numbers: "08/20/32/44"},
          {label: '兔', type: 'B4', numbers: "07/19/31/43"},
          {label: '龙', type: 'B5', numbers: "06/18/30/42"},
          {label: '蛇', type: 'B6', numbers: "05/17/29/41"},
          {label: '马', type: 'B7', numbers: "04/16/28/40"},
          {label: '羊', type: 'B8', numbers: "03/15/27/39"},
          {label: '猴', type: 'B9', numbers: "02/14/26/38"},
          {label: '鸡', type: 'BA', numbers: "01/13/25/37/49"},
          {label: '狗', type: 'BB', numbers: "12/24/36/48"},
          {label: '猪', type: 'BC', numbers: "11/23/35/47"},
        ],
      },
      {
        title: '四肖连',
        data: [
          {label: '鼠', type: 'C1', numbers: "10/22/34/46"},
          {label: '牛', type: 'C2', numbers: "09/21/33/45"},
          {label: '虎', type: 'C3', numbers: "08/20/32/44"},
          {label: '兔', type: 'C4', numbers: "07/19/31/43"},
          {label: '龙', type: 'C5', numbers: "06/18/30/42"},
          {label: '蛇', type: 'C6', numbers: "05/17/29/41"},
          {label: '马', type: 'C7', numbers: "04/16/28/40"},
          {label: '羊', type: 'C8', numbers: "03/15/27/39"},
          {label: '猴', type: 'C9', numbers: "02/14/26/38"},
          {label: '鸡', type: 'CA', numbers: "01/13/25/37/49"},
          {label: '狗', type: 'CB', numbers: "12/24/36/48"},
          {label: '猪', type: 'CC', numbers: "11/23/35/47"},
        ],
      },
      {
        title: '五肖连',
        data: [
          {label: '鼠', type: 'D1', numbers: "10/22/34/46"},
          {label: '牛', type: 'D2', numbers: "09/21/33/45"},
          {label: '虎', type: 'D3', numbers: "08/20/32/44"},
          {label: '兔', type: 'D4', numbers: "07/19/31/43"},
          {label: '龙', type: 'D5', numbers: "06/18/30/42"},
          {label: '蛇', type: 'D6', numbers: "05/17/29/41"},
          {label: '马', type: 'D7', numbers: "04/16/28/40"},
          {label: '羊', type: 'D8', numbers: "03/15/27/39"},
          {label: '猴', type: 'D9', numbers: "02/14/26/38"},
          {label: '鸡', type: 'DA', numbers: "01/13/25/37/49"},
          {label: '狗', type: 'DB', numbers: "12/24/36/48"},
          {label: '猪', type: 'DC', numbers: "11/23/35/47"},
        ],
      },
    ],

  },
  {
    name: '连尾',
    id: 9,
    type: 'lianwei',
    totleTitle: ['二尾碰', '三尾碰', '四尾碰', '五尾碰'],
    tabs: ['LF2', 'LF3', 'LF4', 'LF5'],
    items: [
      {
        title: '二尾碰',
        type: 'LF2',
        data: [
          {label: '尾1', type: 'WA1', numbers: "01/11/21/31/41"},
          {label: '尾2', type: 'WA2', numbers: "02/12/22/32/42"},
          {label: '尾3', type: 'WA3', numbers: "03/13/23/33/43"},
          {label: '尾4', type: 'WA4', numbers: "04/14/24/34/44"},
          {label: '尾5', type: 'WA5', numbers: "05/15/25/35/45"},
          {label: '尾6', type: 'WA6', numbers: "06/16/26/36/46"},
          {label: '尾7', type: 'WA7', numbers: "07/17/27/37/47"},
          {label: '尾8', type: 'WA8', numbers: "08/18/28/38/48"},
          {label: '尾9', type: 'WA9', numbers: "09/19/29/39/49"},
          {label: '尾0', type: 'WA0', numbers: "10/20/30/40"},
        ],
      },
      {
        title: '三尾碰',
        type: 'LF3',
        data: [
          {label: '尾1', type: 'WB1', numbers: "01/11/21/31/41"},
          {label: '尾2', type: 'WB2', numbers: "02/12/22/32/42"},
          {label: '尾3', type: 'WB3', numbers: "03/13/23/33/43"},
          {label: '尾4', type: 'WB4', numbers: "04/14/24/34/44"},
          {label: '尾5', type: 'WB5', numbers: "05/15/25/35/45"},
          {label: '尾6', type: 'WB6', numbers: "06/16/26/36/46"},
          {label: '尾7', type: 'WB7', numbers: "07/17/27/37/47"},
          {label: '尾8', type: 'WB8', numbers: "08/18/28/38/48"},
          {label: '尾9', type: 'WB9', numbers: "09/19/29/39/49"},
          {label: '尾0', type: 'WB0', numbers: "10/20/30/40"},
        ],
      },
      {
        title: '四尾碰',
        type: 'LF4',
        data: [
          {label: '尾1', type: 'WC1', numbers: "01/11/21/31/41"},
          {label: '尾2', type: 'WC2', numbers: "02/12/22/32/42"},
          {label: '尾3', type: 'WC3', numbers: "03/13/23/33/43"},
          {label: '尾4', type: 'WC4', numbers: "04/14/24/34/44"},
          {label: '尾5', type: 'WC5', numbers: "05/15/25/35/45"},
          {label: '尾6', type: 'WC6', numbers: "06/16/26/36/46"},
          {label: '尾7', type: 'WC7', numbers: "07/17/27/37/47"},
          {label: '尾8', type: 'WC8', numbers: "08/18/28/38/48"},
          {label: '尾9', type: 'WC9', numbers: "09/19/29/39/49"},
          {label: '尾0', type: 'WC0', numbers: "10/20/30/40"},
        ],
      },
      {
        title: '五尾碰',
        type: 'LF5',
        data: [
          {label: '尾1', type: 'WD1', numbers: "01/11/21/31/41"},
          {label: '尾2', type: 'WD2', numbers: "02/12/22/32/42"},
          {label: '尾3', type: 'WD3', numbers: "03/13/23/33/43"},
          {label: '尾4', type: 'WD4', numbers: "04/14/24/34/44"},
          {label: '尾5', type: 'WD5', numbers: "05/15/25/35/45"},
          {label: '尾6', type: 'WD6', numbers: "06/16/26/36/46"},
          {label: '尾7', type: 'WD7', numbers: "07/17/27/37/47"},
          {label: '尾8', type: 'WD8', numbers: "08/18/28/38/48"},
          {label: '尾9', type: 'WD9', numbers: "09/19/29/39/49"},
          {label: '尾0', type: 'WD0', numbers: "10/20/30/40"},
        ],
      },
    ],

  },
  {
    name: '自选不中',
    id: 10,
    type: 'zixuanbuzhong',
    totleTitle: ['五不中', '六不中', '七不中', '八不中', '九不中', '十不中', '十一不中', '十二不中'],
    tabs: ['NI5', 'NI6', 'NI7', 'NI8', 'NI9', 'NIA', 'NIB', 'NIC'],
    data: [
      {label:'01'},
      {label:'02'},
      {label:'03'},
      {label:'04'},
      {label:'05'},
      {label:'06'},
      {label:'07'},
      {label:'08'},
      {label:'09'},
      {label:'10'},
      {label:'11'},
      {label:'12'},
      {label:'13'},
      {label:'14'},
      {label:'15'},
      {label:'16'},
      {label:'17'},
      {label:'18'},
      {label:'19'},
      {label:'20'},
      {label:'21'},
      {label:'22'},
      {label:'23'},
      {label:'24'},
      {label:'25'},
      {label:'26'},
      {label:'27'},
      {label:'28'},
      {label:'29'},
      {label:'30'},
      {label:'31'},
      {label:'32'},
      {label:'33'},
      {label:'34'},
      {label:'35'},
      {label:'36'},
      {label:'37'},
      {label:'38'},
      {label:'39'},
      {label:'40'},
      {label:'41'},
      {label:'42'},
      {label:'43'},
      {label:'44'},
      {label:'45'},
      {label:'46'},
      {label:'47'},
      {label:'48'},
      {label:'49'},
    ],
  },
  {
    name: '生肖',
    id: [11,12,13,15],
    type: 'shengxiao',
    totleTitle: ['十二肖', '正肖', '一肖', '总肖'],
    tabs: ['sx', 'zx', 'yx', 'zx'],
    items: [
      {
        title: '十二肖',
        data: [
          {title: '十二肖', label: '鼠', name: 'SP_A1', numbers: "10/22/34/46"},
          {title: '十二肖', label: '牛', name: 'SP_A2', numbers: "09/21/33/45"},
          {title: '十二肖', label: '虎', name: 'SP_A3', numbers: "08/20/32/44"},
          {title: '十二肖', label: '兔', name: 'SP_A4', numbers: "07/19/31/43"},
          {title: '十二肖', label: '龙', name: 'SP_A5', numbers: "06/18/30/42"},
          {title: '十二肖', label: '蛇', name: 'SP_A6', numbers: "05/17/29/41"},
          {title: '十二肖', label: '马', name: 'SP_A7', numbers: "04/16/28/40"},
          {title: '十二肖', label: '羊', name: 'SP_A8', numbers: "03/15/27/39"},
          {title: '十二肖', label: '猴', name: 'SP_A9', numbers: "02/14/26/38"},
          {title: '十二肖', label: '鸡', name: 'SP_AA', numbers: "01/13/25/37/49"},
          {title: '十二肖', label: '狗', name: 'SP_AB', numbers: "12/24/36/48"},
          {title: '十二肖', label: '猪', name: 'SP_AC', numbers: "11/23/35/47"},
        ],
      },
      {
        title: '正肖',
        data: [
          {title: '正肖', label: '鼠', name: 'NA_A1', numbers: "10/22/34/46"},
          {title: '正肖', label: '牛', name: 'NA_A2', numbers: "09/21/33/45"},
          {title: '正肖', label: '虎', name: 'NA_A3', numbers: "08/20/32/44"},
          {title: '正肖', label: '兔', name: 'NA_A4', numbers: "07/19/31/43"},
          {title: '正肖', label: '龙', name: 'NA_A5', numbers: "06/18/30/42"},
          {title: '正肖', label: '蛇', name: 'NA_A6', numbers: "05/17/29/41"},
          {title: '正肖', label: '马', name: 'NA_A7', numbers: "04/16/28/40"},
          {title: '正肖', label: '羊', name: 'NA_A8', numbers: "03/15/27/39"},
          {title: '正肖', label: '猴', name: 'NA_A9', numbers: "02/14/26/38"},
          {title: '正肖', label: '鸡', name: 'NA_AA', numbers: "01/13/25/37/49"},
          {title: '正肖', label: '狗', name: 'NA_AB', numbers: "12/24/36/48"},
          {title: '正肖', label: '猪', name: 'NA_AC', numbers: "11/23/35/47"},
        ],
      },
      {
        title: '一肖',
        data: [
          {title: '一肖', label: '鼠', name: 'SP_B1', numbers: "10/22/34/46"},
          {title: '一肖', label: '牛', name: 'SP_B2', numbers: "09/21/33/45"},
          {title: '一肖', label: '虎', name: 'SP_B3', numbers: "08/20/32/44"},
          {title: '一肖', label: '兔', name: 'SP_B4', numbers: "07/19/31/43"},
          {title: '一肖', label: '龙', name: 'SP_B5', numbers: "06/18/30/42"},
          {title: '一肖', label: '蛇', name: 'SP_B6', numbers: "05/17/29/41"},
          {title: '一肖', label: '马', name: 'SP_B7', numbers: "04/16/28/40"},
          {title: '一肖', label: '羊', name: 'SP_B8', numbers: "03/15/27/39"},
          {title: '一肖', label: '猴', name: 'SP_B9', numbers: "02/14/26/38"},
          {title: '一肖', label: '鸡', name: 'SP_BA', numbers: "01/13/25/37/49"},
          {title: '一肖', label: '狗', name: 'SP_BB', numbers: "12/24/36/48"},
          {title: '一肖', label: '猪', name: 'SP_BC', numbers: "11/23/35/47"},
        ],
      },
      {
        title: '总肖',
        data: [
          {title: '总肖', label: '234肖', name: 'TX2'},
          {title: '总肖', label: '5肖', name: 'TX5'},
          {title: '总肖', label: '6肖', name: 'TX6'},
          {title: '总肖', label: '7肖', name: 'TX7'},
          {title: '总肖', label: '总肖单', name: 'TX_ODD'},
          {title: '总肖', label: '总肖双', name: 'TX_EVEN'},
        ],
      },
    ],
  },
  {
    name: '合肖',
    id: [14],
    type: 'hexiao',
    totleTitle: ['中', '不中'],
    tabs: ['NX_IN', 'NX_OUT'],
    items: [
      {
        title: '中',
        data: [
          {title: '中', label: '鼠', name: 'NX_A1', numbers: "10/22/34/46"},
          {title: '中', label: '牛', name: 'NX_A2', numbers: "09/21/33/45"},
          {title: '中', label: '虎', name: 'NX_A3', numbers: "08/20/32/44"},
          {title: '中', label: '兔', name: 'NX_A4', numbers: "07/19/31/43"},
          {title: '中', label: '龙', name: 'NX_A5', numbers: "06/18/30/42"},
          {title: '中', label: '蛇', name: 'NX_A6', numbers: "05/17/29/41"},
          {title: '中', label: '马', name: 'NX_A7', numbers: "04/16/28/40"},
          {title: '中', label: '羊', name: 'NX_A8', numbers: "03/15/27/39"},
          {title: '中', label: '猴', name: 'NX_A9', numbers: "02/14/26/38"},
          {title: '中', label: '鸡', name: 'NX_AA', numbers: "01/13/25/37/49"},
          {title: '中', label: '狗', name: 'NX_AB', numbers: "12/24/36/48"},
          {title: '中', label: '猪', name: 'NX_AC', numbers: "11/23/35/47"},
        ],
      },
      {
        title: '不中',
        data: [
          {title: '不中', label: '鼠', name: 'NX_A1', numbers: "10/22/34/46"},
          {title: '不中', label: '牛', name: 'NX_A2', numbers: "09/21/33/45"},
          {title: '不中', label: '虎', name: 'NX_A3', numbers: "08/20/32/44"},
          {title: '不中', label: '兔', name: 'NX_A4', numbers: "07/19/31/43"},
          {title: '不中', label: '龙', name: 'NX_A5', numbers: "06/18/30/42"},
          {title: '不中', label: '蛇', name: 'NX_A6', numbers: "05/17/29/41"},
          {title: '不中', label: '马', name: 'NX_A7', numbers: "04/16/28/40"},
          {title: '不中', label: '羊', name: 'NX_A8', numbers: "03/15/27/39"},
          {title: '不中', label: '猴', name: 'NX_A9', numbers: "02/14/26/38"},
          {title: '不中', label: '鸡', name: 'NX_AA', numbers: "01/13/25/37/49"},
          {title: '不中', label: '狗', name: 'NX_AB', numbers: "12/24/36/48"},
          {title: '不中', label: '猪', name: 'NX_AC', numbers: "11/23/35/47"},
        ],
      },
    ],
  },
  {
    name: '色波',
    id: [16,17,18,19],
    type: 'sebo',
    totleTitle: ['三色波', '半波', '半半波', '七色波'],
    tabs: ['ssb', 'bb', 'bbb', 'qsb'],
    items: [
      {
        title: '三色波',
        data: [
          {title: '三色波', label: '红波', color: 'R', name: 'SP_R'},
          {title: '三色波', label: '绿波', color: 'G', name: 'SP_G'},
          {title: '三色波', label: '蓝波', color: 'B', name: 'SP_B'},
        ],
      },
      {
        title: '半波',
        data: [
          {title: '半波', label: '红单', color: 'R', name: 'HB_RODD'},
          {title: '半波', label: '红双', color: 'R', name: 'HB_REVEN'},
          {title: '半波', label: '红大', color: 'R', name: 'HB_ROVER'},
          {title: '半波', label: '红小', color: 'R', name: 'HB_RUNDER'},
          {title: '半波', label: '绿单', color: 'G', name: 'HB_GODD'},
          {title: '半波', label: '绿双', color: 'G', name: 'HB_GEVEN'},
          {title: '半波', label: '绿大', color: 'G', name: 'HB_GOVER'},
          {title: '半波', label: '绿小', color: 'G', name: 'HB_GUNDER'},
          {title: '半波', label: '蓝单', color: 'B', name: 'HB_BODD'},
          {title: '半波', label: '蓝双', color: 'B', name: 'HB_BEVEN'},
          {title: '半波', label: '蓝大', color: 'B', name: 'HB_BOVER'},
          {title: '半波', label: '蓝小', color: 'B', name: 'HB_BUNDER'},
        ],
      },
      {
        title: '半半波',
        data: [
          {title: '半半波', label: '红大单', color: 'R', name: 'HH_ROO'},
          {title: '半半波', label: '红大双', color: 'R', name: 'HH_ROE'},
          {title: '半半波', label: '红小单', color: 'R', name: 'HH_RUO'},
          {title: '半半波', label: '红小双', color: 'R', name: 'HH_RUE'},
          {title: '半半波', label: '绿大单', color: 'G', name: 'HH_GOO'},
          {title: '半半波', label: '绿大双', color: 'G', name: 'HH_GOE'},
          {title: '半半波', label: '绿小单', color: 'G', name: 'HH_GUO'},
          {title: '半半波', label: '绿小双', color: 'G', name: 'HH_GUE'},
          {title: '半半波', label: '蓝大单', color: 'B', name: 'HH_BOO'},
          {title: '半半波', label: '蓝大双', color: 'B', name: 'HH_BOE'},
          {title: '半半波', label: '蓝小单', color: 'B', name: 'HH_BUO'},
          {title: '半半波', label: '蓝小双', color: 'B', name: 'HH_BUE'},
        ],
      },
      {
        title: '七色波',
        data: [
          {title: '七色波', label: '红波', color: 'R', name: 'C7_R'},
          {title: '七色波', label: '绿波', color: 'G', name: 'C7_G'},
          {title: '七色波', label: '蓝波', color: 'B', name: 'C7_B'},
          {title: '七色波', label: '和局', color: 'R', name: 'C7_N'},
        ],
      },
    ],
  },
  {
    name: '尾数',
    id: [20,21],
    type: 'weishu',
    totleTitle: ['头尾数', '正特尾数'],
    tabs: ['tws', 'ztws'],
    items: [
      {
        title: '头尾数',
        data: [
          {title: '头尾数', label: '头0', name: 'SH0'},
          {title: '头尾数', label: '头1', name: 'SH1'},
          {title: '头尾数', label: '头2', name: 'SH2'},
          {title: '头尾数', label: '头3', name: 'SH3'},
          {title: '头尾数', label: '头4', name: 'SH4'},
          {title: '头尾数', label: '尾0', name: 'SF0'},
          {title: '头尾数', label: '尾1', name: 'SF1'},
          {title: '头尾数', label: '尾2', name: 'SF2'},
          {title: '头尾数', label: '尾3', name: 'SF3'},
          {title: '头尾数', label: '尾4', name: 'SF4'},
          {title: '头尾数', label: '尾5', name: 'SF5'},
          {title: '头尾数', label: '尾6', name: 'SF6'},
          {title: '头尾数', label: '尾7', name: 'SF7'},
          {title: '头尾数', label: '尾8', name: 'SF8'},
          {title: '头尾数', label: '尾9', name: 'SF9'},
        ],
      },
      {
        title: '正特尾数',
        data: [
          {title: '正特尾数', label: '尾0', name: 'NF0'},
          {title: '正特尾数', label: '尾1', name: 'NF1'},
          {title: '正特尾数', label: '尾2', name: 'NF2'},
          {title: '正特尾数', label: '尾3', name: 'NF3'},
          {title: '正特尾数', label: '尾4', name: 'NF4'},
          {title: '正特尾数', label: '尾5', name: 'NF5'},
          {title: '正特尾数', label: '尾6', name: 'NF6'},
          {title: '正特尾数', label: '尾7', name: 'NF7'},
          {title: '正特尾数', label: '尾8', name: 'NF8'},
          {title: '正特尾数', label: '尾9', name: 'NF9'},
        ],
      },
    ],
  },
  {
    name: '七码五行',
    id: 22,
    type: 'qimawuxing',
    totleTitle: ['七码', '五行'],
    items: [
      {
        title: '七码',
        data: [
          {title: '七码', label: '单0双7', name: 'S7_0O7E'},
          {title: '七码', label: '大0小7', name: 'S7_0O7U'},
          {title: '七码', label: '单1双6', name: 'S7_1O6E'},
          {title: '七码', label: '大1小6', name: 'S7_1O6U'},
          {title: '七码', label: '单2双5', name: 'S7_2O5E'},
          {title: '七码', label: '大2小5', name: 'S7_2O5U'},
          {title: '七码', label: '单3双4', name: 'S7_3O4E'},
          {title: '七码', label: '大3小4', name: 'S7_3O4U'},
          {title: '七码', label: '单4双3', name: 'S7_4O3E'},
          {title: '七码', label: '大4小3', name: 'S7_4O3U'},
          {title: '七码', label: '单5双2', name: 'S7_5O2E'},
          {title: '七码', label: '大5小2', name: 'S7_5O2U'},
          {title: '七码', label: '单6双1', name: 'S7_6O1E'},
          {title: '七码', label: '大6小1', name: 'S7_6O1U'},
          {title: '七码', label: '单7双0', name: 'S7_7O0E'},
          {title: '七码', label: '大7小0', name: 'S7_7O0U'},
        ],
      },
      {
        title: '五行',
        data: [
          {title: '五行', label: '金', number: '03,04,17,18,25,26,33,34,47,48', name: 'F_METAL'},
          {title: '五行', label: '木', number: '07,08,15,16,29,30,37,38,45,46', name: 'F_WOOD'},
          {title: '五行', label: '水', number: '05,06,13,14,21,22,35,36,43,44', name: 'F_WATER'},
          {title: '五行', label: '火', number: '01,02,09,10,23,24,31,32,39,40', name: 'F_FIRE'},
          {title: '五行', label: '土', number: '11,12,19,20,27,28,41,42,49', name: 'F_EARTH'},
        ],
      },
    ],

  },
  {
    name: '中一',
    id: 23,
    type: 'zhongyi',
    totleTitle: ['五中一', '六中一', '七中一', '八中一', '九中一', '十中一'],
    tabs: ['IN15', 'IN16', 'IN17', 'IN18', 'IN19', 'NI1A'],
    data: [
      {label:'01'},
      {label:'02'},
      {label:'03'},
      {label:'04'},
      {label:'05'},
      {label:'06'},
      {label:'07'},
      {label:'08'},
      {label:'09'},
      {label:'10'},
      {label:'11'},
      {label:'12'},
      {label:'13'},
      {label:'14'},
      {label:'15'},
      {label:'16'},
      {label:'17'},
      {label:'18'},
      {label:'19'},
      {label:'20'},
      {label:'21'},
      {label:'22'},
      {label:'23'},
      {label:'24'},
      {label:'25'},
      {label:'26'},
      {label:'27'},
      {label:'28'},
      {label:'29'},
      {label:'30'},
      {label:'31'},
      {label:'32'},
      {label:'33'},
      {label:'34'},
      {label:'35'},
      {label:'36'},
      {label:'37'},
      {label:'38'},
      {label:'39'},
      {label:'40'},
      {label:'41'},
      {label:'42'},
      {label:'43'},
      {label:'44'},
      {label:'45'},
      {label:'46'},
      {label:'47'},
      {label:'48'},
      {label:'49'},
    ],
  },
]


export default layout
